### ISSUE TITLE
lightbox flow: content is not centered on screen when viewed on a mobile device

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-relier-client#10]
![screen shot 2014-12-12 at 10 11 14](https://cloud.githubusercontent.com/assets/848085/5409946/5c169cec-81e7-11e4-93c9-b19a4c589ca7.png)

**Comment by shane-tomlinson** [comment]
@kumar303 or @andymckay - are you guys using the lightbox from the relier client with the payments flow? Are you using the relier client?

**Comment by kumar303** [comment]
@shane-tomlinson yes we are but really only in our example application at the minute. We haven't tested much on mobile yet.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-relier-client/issues/81
