### ISSUE TITLE
Allow reliers to notify FxA content server when the user logs out

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-relier-client#2]
I imagine such a thing would work via some hidden iframe. 

Logouts are hard. The idea is that if the user is signaling her logout intent, then we should probably require the user's FxA password for future FxA logins to reliers. This mechanism would allow reliers to notify us of logout events.

**Comment by shane-tomlinson** [comment]
This is a pretty high level request and should be a user story in Aha or the fxa repo, if it's still needed.
