### ISSUE TITLE
API.md mentions a "FirefoxAPI" class that doesn't seem to exist

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-relier-client#26]
Skimming the API docs, it says that I should do `var fxapi = new FirefoxAPI(...)` to get started.  But grep tells me this is the only occurrence of `FirefoxAPI` in the whole repo.  Has it been renamed?

**Comment by shane-tomlinson** [comment]
@rfk - doh, a brand new library and the docs are already out of date.

**Comment by vladikoff** [comment]
@shane-tomlinson there is an option to move all docs to generated docs, i.e move API.md examples to YUIdocs using the `@example` syntax: http://yui.github.io/yuidoc/syntax/#example
