### ISSUE TITLE
Integrate with the FirefoxOS native experience.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-relier-client#33]

**Comment by kumar303** [comment]
Can you provide more information on this? Would this feature allow a user who is *already* logged in natively to a Firefox OS device to use a relier-client powered app without having to log in again?

**Comment by SamPenrose** [comment]
We might want a higher-bandwidth medium for this explanation, but briefly: there will be no "already". When the user first gets a FxOS 3.0 device, it will implement FxA using the relier library. FxOS has fixed cross-app OAuth to allow SSO; if need be we can also feature-detect navigator.mozID and silently use it, though my advice would be to remove it.

**Comment by vladikoff** [comment]
Closing until this is needed or is part of some requirement
