### ISSUE TITLE
Remove version from code

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-relier-client#35]
Ref: 
https://github.com/mozilla/fxa-relier-client/blob/6ffbbf339c339b470db662e0033c978a101d1bb5/client/FxaRelierClient.js#L165

We need to make sure we keep this up to date with the releases

```javascript
  FxaRelierClient.prototype = {
    /**
     * FxaRelierClient version
     *
     * @property version
     * @type {String}
     */
    version: '0.0.0'
  };
```

**Comment by vladikoff** [comment]
Find a way to update the version with each release...

**Comment by shane-tomlinson** [comment]
Is version even needed? If not, kill it.
