### ISSUE TITLE
Add MDN documentation.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-relier-client#37]

**Comment by vladikoff** [comment]
There might be a way to auto generate an article from YUIDoc documentation that we already have.

**Comment by shane-tomlinson** [comment]
@vladikoff - that would be ever so hot.

**Comment by vladikoff** [comment]
Here is the MDN PUT API https://developer.mozilla.org/en-US/docs/User:lmorchard/PUT-API

**Comment by vladikoff** [comment]
and https://developer.mozilla.org/en-US/docs/MDN/Kuma/API

**Comment by shane-tomlinson** [comment]
The PUT API looks like it fits well for our use case.

**Comment by shane-tomlinson** [comment]
Basic MDN documentation added, manually.

**Comment by vladikoff** [comment]
Link?

**Comment by shane-tomlinson** [comment]
https://developer.mozilla.org/Firefox_Accounts#Login_with_the_FxA_OAuth_Javascript_library

**Comment by shane-tomlinson** [comment]
Closing this, #43 opened as follow on.

**Comment by vladikoff** [comment]
> Next, ensure the API is being called correctly; full API documentation is available on GitHub

:+1:
