### ISSUE TITLE
Add ability to pass along a `campaign` parameter

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-relier-client#51]
`campaign` is used in metrics to know whether the user is authenticating as part of a marketing effort.

Link to https://github.com/mozilla/fxa-content-server/issues/1898

**Comment by vladikoff** [comment]
@shane-tomlinson do we still need this?

**Comment by shane-tomlinson** [comment]
It's part of our supported API (as are all the utm_*) params, so it'd be
nice to stay consistent. Though the Growth team is not using the relier
client, so no immediate customers.

**Comment by vladikoff** [comment]
> Though the Growth team is not using the relier
client, so no immediate customers.

The Growth team should be using `utm_campaign`. Should we close this and discontinue supporting "campaign"?

**Comment by shane-tomlinson** [comment]
> The Growth team should be using utm_campaign. Should we close this and discontinue supporting "campaign"?

That's a valid question. Having one way to do things would certainly be nice.

**Comment by vladikoff** [comment]
Last I heard Growth team is not using relier client. and we are planning to drop `campaign` param. Closing
