### ISSUE TITLE
grunt build fails

### ISSUE THREAD

**Issue by tarekziade** [mozilla/fxa-relier-client#53]
Following README, I get this:

```sh
tarekz:fxa-relier-client tarek$ grunt build
Loading "watch.js"  (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "jshint:config" (jshint) task
>> 16 files lint free.

Running "jshint:app" (jshint) task
>> 15 files lint free.

Running "jscs:src" (jscs) task
>> 31 files without code style errors.

Running "requirejs:prod" (requirejs) task
{ [Error: Error: ERROR: module path does not exist: /Users/tarek/Dev/github.com/fxa-relier-client/components/almond/almond.js for module named: components/almond/almond. Path is relative to: /Users/tarek/Dev/github.com/fxa-relier-client
    at /Users/tarek/Dev/github.com/fxa-relier-client/node_modules/grunt-contrib-requirejs/node_modules/requirejs/bin/r.js:26824:35
]
  originalError: [Error: ERROR: module path does not exist: /Users/tarek/Dev/github.com/fxa-relier-client/components/almond/almond.js for module named: components/almond/almond. Path is relative to: /Users/tarek/Dev/github.com/fxa-relier-client] }
```

**Comment by tarekziade** [comment]
I fixed it by running

```sh
$ bower install almond
```

Why do we have to user two differents package managers ? I am quite confused

**Comment by pdehaan** [comment]
Weird, the bower module should have been automatically installed when you ran `npm install` (via [package.json](https://github.com/mozilla/fxa-relier-client/blob/5cead9895e00a606007649019f19f81bbfdc5e4c/package.json#L13)'s handy `postinstall` script).

---

> **Re:** _Why do we have to use two differents package managers ? I am quite confused_

We use bower to manage front-end modules, versus npm for node modules.

**Comment by shane-tomlinson** [comment]
Closing as self-fixed.

> We use bower to manage front-end modules, versus npm for node modules.

Spot on.

**Comment by shane-tomlinson** [comment]
> We use bower to manage front-end modules, versus npm for node modules.

As an aside, we have a `postinstall` script defined [in package.json](https://github.com/mozilla/fxa-relier-client/blob/770d17876aa687057b1577e9b678c93197d4c2cb/package.json#L13) to automatically install the bower components. Did this not happen?

**Comment by tarekziade** [comment]
I am going to reopen this one because as the doc stands, running grunt build fails.

**Comment by pdehaan** [comment]
@tarekziade What steps did you use?

I did a `git clone ...` then `npm install` then `grunt build` and everything worked for me:

```
$ grunt build
Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "jshint:config" (jshint) task
>> 16 files lint free.

Running "jshint:app" (jshint) task
>> 15 files lint free.

Running "jscs:src" (jscs) task
>> 31 files without code style errors.

Running "requirejs:prod" (requirejs) task

Running "requirejs:debug" (requirejs) task

Running "bytesize:all" (bytesize) task

build/fxa-relier-client.js
Size:		76.00 Kb
Gzip Size:	17.23 Kb

build/fxa-relier-client.min.js
Size:		20.52 Kb
Gzip Size:	7.18 Kb

Done, without errors.
```

**Comment by vladikoff** [comment]
Inactive issue. Needs more info as well. See successful CI output for more details that might help https://travis-ci.org/mozilla/fxa-relier-client
