### ISSUE TITLE
Release 0.0.8

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-relier-client#59]
@shane-tomlinson could we get a new release of the relier-client?

Need these changes https://github.com/mozilla/fxa-relier-client/commit/2dec9d43aa41a797a2c2bf341535f578685308df, will update 123done so teamcity tests pass

**Comment by shane-tomlinson** [comment]
Released: https://github.com/mozilla/fxa-relier-client/tree/0.0.8
