### ISSUE TITLE
CORS error from fxaRelierClient.token.tradeCode()

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa-relier-client#61]
When running this from release 590b2ab4f4 of the JS lib, ``fxaRelierClient.token.tradeCode(returnedCode)``, the call failed because of a CORS error. In Firefox it says that the ``x-requested-with`` header was not sent which causes the failure. Should be an easy fix. I tried making the same post to https://oauth-stable.dev.lcip.org/v1/token with jQuery (which I think sets that header automatically) and it worked.

**Comment by vladikoff** [comment]
@kumar303 does this happen with an older version of the relier-client?

**Comment by kumar303** [comment]
which version should I try?

**Comment by vladikoff** [comment]
@kumar303 try https://github.com/mozilla/fxa-relier-client/releases/tag/0.0.7
Sorry I assumed when you said "When running this from release" I thought something broke. 
Did `tradeCode` ever work for you?

**Comment by kumar303** [comment]
No, this is my first time trying it.

**Comment by kumar303** [comment]
Also, with release 590b2ab this exact code produces a blank error string:
````
      fxaRelierClient.token.tradeCode(result.code)
        .then(function (token) {
          console.log('got token:', token);
        }, function(err) {
          console.error('token failure:', err);
        });
````

 The value of ``err`` is ``""`` even though I can see the CORS error in the console: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oauth-stable.dev.lcip.org/v1/token. (Reason: missing token 'x-requested-with' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel)."

**Comment by kumar303** [comment]
I can confirm that the same exact thing happens with version 0.0.7

**Comment by shane-tomlinson** [comment]
@kumar303 - are you doing this from within a web page? `tradeCode` is meant to be a server side only call since relies on knowing the `client_secret`.

**Comment by kumar303** [comment]
ah, I see. I was doing it in a web page but only because it's a throw-away example app that I didn't want to run a server for. I was surprised to see the method available to web pages but I didn't realize that the same code is used server side so that makes sense.

**Comment by kumar303** [comment]
since this doesn't apply to the client side, I'll close

**Comment by shane-tomlinson** [comment]
Thanks for bringing it up @kumar303, we need to document that this function should *not* be used client side. (@vladikoff already opened #62)
