### ISSUE TITLE
Support installation via `npm install`

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa-relier-client#67]
Some clientside toolchains (like ours) use npm packages exclusively and this works well with webpack and other tools. It would be nice to not rely on bower just for this package. Would it be possible to publish packages to npm in addition to bower?

Or is it there already? I get:
````
$ npm install fxa-relier-client
...
npm ERR! 404 Not Found: fxa-relier-client
npm ERR! 404
npm ERR! 404 'fxa-relier-client' is not in the npm registry.
````
Or is it better to just install from a git URL?

**Comment by vladikoff** [comment]
Done.

**Comment by kumar303** [comment]
Thanks!
