### ISSUE TITLE
Cannot do require('fxa-relier-client') using WebPack

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa-relier-client#68]
Thanks for publishing the client to npm (https://github.com/mozilla/fxa-relier-client/issues/67) but we're unable to run the code using `require()` on the [payments-ui](https://github.com/mozilla/payments-ui) (which runs in a web browser). Is it possible to fix up the module for this?

Here is a simple case that reproduces the errors we see: https://dl.dropboxusercontent.com/u/254355/tmp/fxa-relier-packaging.zip

Unzip that directory, cd in and do this:
* `npm install`
* `grunt build`
* then open `index.html` in a web browser

My call to `require('fxa-relier-client')` results in `Error: Cannot find module '/client/FxaRelierClient.js'.`

I tried a couple things to work around the issue (e.g. adding resolve paths to `webpack.config.js`) but ultimately it leads to failures somewhere farther down the stack. I got as far as where `p-promise` was loading but failing because its test dependency `expect.js` wasn't there (which shouldn't be anyway).

Here are some reasons we'd like to use the client lib this way:
* we don't rely on bower anywhere in our stack
* we'd like to create a single minified bundle and using [webpack](http://webpack.github.io/) with common JS is the easiest way to do so
* it should be straight forward to fix up the module to support commonJS (I think)

Note also that similar errors occur if I install the client lib with bower and try to require the module from that directory.

**Comment by shane-tomlinson** [comment]
@kumar303 - The library should be set up to support at a minimum Node based CommonJS, you can go to the library's root directory and do a `node ./node/index.js`, or create a shell project, `npm install fxa-relier-client` and use this as index.js:

```js
var relierClient = require('fxa-relier-client');
```

Then `node ./index.js`. No problems.

**Comment by shane-tomlinson** [comment]
@kumar303 - have you tried loading `node/index.js` instead of the package's root directory? Perhaps that fixes the problem?

**Comment by kumar303** [comment]
Hmm, I'm not sure I understand. We are running a web application in the browser and would like to use the fxa client library to show the lightbox login on a web page, not in node.

**Comment by vladikoff** [comment]
@kumar303 have you tried loading the built .js file with WebPack's noParse mode?

**Comment by kumar303** [comment]
Aha, I didn't know about `noParse`, however, it doesn't seem to be doing exactly what I'm thinking. In the example app I posted above, I ran `bower install fxa-relier-client` then changed this in the webpack config:
````
  module: {
    noParse: [
      path.join(__dirname, 'bower_components/fxa-relier-client/fxa-relier-client.js'),
    ],
    ...
  },
  resolve: {
    modulesDirectories: [
      'public/js/',
      'node_modules',
      'bower_components/fxa-relier-client/',
    ],
  },
````

Loading index.html I now get: `Error: client/auth/api missing p-promise` from the call to `require('fxa-relier-client')`

Is `p-promise` not included in the bower installed file? I guess webpack isn't parsing it but maybe the runtime call to require() is?

**Comment by kumar303** [comment]
hmm, I don't think `noParse` will help because of this in [the docs](http://webpack.github.io/docs/configuration.html#module-noparse): "The files are expected to have no call to require, define or similar"

**Comment by shane-tomlinson** [comment]
@kumar303 - We'll have to get it on priority queue so we can set aside half a day to figure out why it's not working in Webpack. I don't know enough about how Webpack works to quickly come up with a fix.

**Comment by kumar303** [comment]
Thanks, that would be helpful. We can just jam it into the page with a script tag for now but we're using it on a public facing site so it would be nice to include it our main JS bundle.

**Comment by shane-tomlinson** [comment]
The problem here is the way p-promise creates itself. I'm not sure of the best way to resolve this.

If I swap the order of [the two branches that create p-promise here](https://github.com/rkatic/p/blob/5a75ebf5ded9c2ec926e332e482ae878d0506df6/p.js#L11-L17), WebPack seems to work as expected. I'm not sure what repercussions that has elsewhere. :/

**Comment by kumar303** [comment]
would it be easy to use https://github.com/jakearchibald/es6-promise maybe?

**Comment by shane-tomlinson** [comment]
> would it be easy to use https://github.com/jakearchibald/es6-promise maybe?

Funny, I had a look at that yesterday to see whether it'd work for me. I didn't dig in far enough to find out definitively.

**Comment by vladikoff** [comment]
Let's explore switching to /es6-promise and checking if that works with WebPack better.

**Comment by ferjm** [comment]
I saw the same issue using Browserify instead of WebPack.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-relier-client/issues/81
