### ISSUE TITLE
YUIDoc API docs looking odd

### ISSUE THREAD

**Issue by 6a68** [mozilla/fxa-relier-client#71]
Looks like the `Lightbox` function signature is slightly munged:

http://mozilla.github.io/fxa-relier-client/classes/Lightbox.html

<img width="463" alt="screenshot 2015-09-01 12 41 47" src="https://cloud.githubusercontent.com/assets/96396/9614479/e396395a-50a6-11e5-849b-19873f9cb97d.png">

**Comment by pdehaan** [comment]
FWIW, `Lightbox#load()` is mildly ugly too:

![lightbox_-_fxa-relier-client](https://cloud.githubusercontent.com/assets/557895/9615059/b650a2f6-50aa-11e5-9ac0-bcf4cc9b069c.png)
