### ISSUE TITLE
Consider deprecating the library

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-relier-client#81]
One of the original goals of the library was to hide the iframe origin check postMessage dance. Now that support for iframing has been removed, that reason no longer exists. Should we deprecate the library?

ref #80

**Comment by vladikoff** [comment]
need to `npm deprecate` it maybe?

**Comment by vladikoff** [comment]
added https://github.com/mozilla/fxa-relier-client/commit/942abd2ee3bebe7627d1046c52cf7159becff778
